language: python
python:
  - "2.7"
install:
  - python --version
  - pip install -U pip
  - easy_install distribute
  - pip install --upgrade distribute
  - pip install -U pytest
  - pip install codecov
# command to run tests
script: nosetests
